on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to Cloudflare Pages
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: mkdir dist && cp index.html dist

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: miy-h
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
